### ISSUE TITLE
Vector index read error 

### ISSUE THREAD

**Issue by HeyHouBenjo** [rmordechay/glsl-plugin-idea#36]
![image](https://github.com/user-attachments/assets/012c7740-7efc-423f-ae1f-7a6889a9c6dd)
Assigning a vector component by index works fine, but reading/copying gives an error message about incompatible types. The same happens for uvec3, where it should read a uint

**Comment by walt-grace** [comment]
@HeyHouBenjo Thanks for reporting. I looked exactly for this kind of bugs. I will fix it and release in the next day a new version. I'm working on error messages and in the next release there would be also the ability to disable the error.

**Comment by rmordechay** [comment]
@HeyHouBenjo Is everything working as expected? Can I close the ticket?

**Comment by HeyHouBenjo** [comment]
After updating from 1.1.2 to 1.1.3, the scenario shown above does not show an error anymore, as expected.

**Comment by HeyHouBenjo** [comment]
![image](https://github.com/user-attachments/assets/c683f489-3a28-455e-a121-89687c78fb0b)

I reopen the issue because the error is not fixed for this case, where there is a bit of nesting involved.
